name: JR Delay Notifier

on:
  schedule:
    - cron: "*/5 * * * *"   # 5分ごとに実行（UTC基準）
  workflow_dispatch:        # 手動実行も可能

jobs:
  run-script:
    runs-on: ubuntu-latest   # 実行環境（Linux）
    steps:
      - uses: actions/checkout@v4   # リポジトリのコードを取得
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"    # Pythonのバージョン
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python main.py
